PORT: int = 8000
IMAGE_WIDTH: int = 500
IMAGE_HEIGHT: int = 500
EGG_SIZE: int = 400
DPI: int = 100
UPLOAD_PATH: str='uploads/'
FORT_PATH: str = "fonts/PequenaPro-Regular.ttf"
RU_BANNED_WORDS_PATH: str= "pre_process/ru_words.txt"
EN_BANNED_WORDS_PATH: str = "pre_process/en_words.txt"
